version: "3"
services:
  nginx:
    image: nginx:alpine
    container_name: (app-name)-nginx
    ports:
      - 80:80
      - 443:443
    expose:
      - 80
      - 443
    volumes:
      - ./nginx/conf/default.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/cert/server.crt:/etc/nginx/cert/server.crt
      - ./nginx/cert/server.key:/etc/nginx/cert/server.key
    depends_on:
      - (app_name_be)
      - (app_name_fe)
  app_name_fe:
    build: ./frontend
    container_name: app_name_fe
    ports:
      - 3000:3000
    restart: always
    depends_on:
      - app_name_be
  app_name_be:
    build: ./backend
    container_name: app_name_be
    ports:
      - 8000:8000
    volumes:
      - ./backend:/code
    env_file:
      - ./backend/.env
  scheduler:
    build: ./scheduler
    container_name: scheduler
    volumes:
      - ./scheduler:/code
    env_file:
      - ./scheduler/.env
    depends_on:
      - app_name_be
